"""Initial migration

Revision ID: 0babf713b216
Revises: 
Create Date: 2026-09-03 16:29:24.942422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0babf713b216'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', name='status'), nullable=True),
    sa.Column('booking_time', sa.DateTime(), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('comes_from', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_reference_id'), ['reference_id'], unique=True)

    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('complaint_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', name='status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('comes_from', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('ease_of_use', sa.Integer(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('prescription_img', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ATTENDED', 'NO_SHOW', name='status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('comes_from', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('ocr_extracted_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('services_mentioned', sa.String(length=500), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deletion_reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('patient_instructions', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('alias_name', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('sample_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('page_id', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'platform_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('message_limit', sa.Integer(), nullable=False),
    sa.Column('message_used', sa.Integer(), nullable=False),
    sa.Column('grace_limit', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('renew_count', sa.Integer(), nullable=False),
    sa.Column('last_renewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('laboratory_id')
    )
    op.create_table('clients',
    sa.Column('sender_id', sa.String(length=100), nullable=False),
    sa.Column('page_id', sa.String(length=100), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=200), nullable=True),
    sa.Column('last_bot_reply', sa.String(length=200), nullable=True),
    sa.Column('chat_history', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['page_id', 'platform_id'], ['pages.page_id', 'pages.platform_id'], ),
    sa.PrimaryKeyConstraint('sender_id', 'page_id', 'platform_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    op.drop_table('subscriptions')
    op.drop_table('pages')
    op.drop_table('lab_services')
    op.drop_table('inquiries')
    op.drop_table('users')
    op.drop_table('platforms')
    op.drop_table('laboratories')
    op.drop_table('feedbacks')
    op.drop_table('complaints')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_reference_id'))

    op.drop_table('bookings')
    # ### end Alembic commands ###
