"""add a Bundle table

Revision ID: 1c4679efef8d
Revises: 1453bc29a11c
Create Date: 2026-09-24 02:37:01.700889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4679efef8d'
down_revision = '1453bc29a11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('lab_services', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('bundle')
    # ### end Alembic commands ###
