"""add table to gmail sent cerdincals

Revision ID: 37c6904704ba
Revises: 0babf713b216
Create Date: 2026-09-07 17:23:07.453261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c6904704ba'
down_revision = '0babf713b216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('gmail_token_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_settings')
    # ### end Alembic commands ###
