"""add a instructionss  to bundle table

Revision ID: 5845382105e1
Revises: f3f134715f86
Create Date: 2026-09-24 13:42:13.191791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5845382105e1'
down_revision = 'f3f134715f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))
        batch_op.drop_column('intructions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intructions', mysql.TEXT(), nullable=True))
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
