"""add a price to bundle table

Revision ID: 910724b5f37c
Revises: 1c4679efef8d
Create Date: 2026-09-24 03:12:21.721254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910724b5f37c'
down_revision = '1c4679efef8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
