"""add a instructions  to bundle table

Revision ID: f3f134715f86
Revises: 910724b5f37c
Create Date: 2026-09-24 13:37:46.939662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f134715f86'
down_revision = '910724b5f37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bundle', schema=None) as batch_op:
        batch_op.drop_column('intructions')

    # ### end Alembic commands ###
